export default {
    ADD_LINK: "ADD_LINK",
    REMOVE_LINK: "REMOVE_LINK",
    UP_VOTE: "UP_VOTE",
    DOWN_VOTE: "DOWN_VOTE",
    ORDER_BY_ASC: "ORDER_BY_ASC",
    ORDER_BY_DESC: "ORDER_BY_DESC",
    ORDER_BY_DEFAULT: "ORDER_BY_DEFAULT"
};